name: livekit_example
description: Example app that uses LiveKit Flutter SDK
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1
  flutter_background: ^1.1.0
  permission_handler: ^10.2.0
  provider: ^6.0.1
  logging: ^1.0.1
  shared_preferences: ^2.0.7
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5

  livekit_client:
    path: ../

    # git:
    #   url: https://github.com/livekit/client-sdk-flutter
    #   ref: main

dependency_overrides: 
  sdp_transform:
    path: /Users/pl/Documents/open-source/forks/dart-sdp-transform
  platform_detect:
    git:
      url: https://github.com/powntheep/platform_detect.git
      ref: master
  device_info_plus: 
    git:
      url: https://github.com/powntheep/plus_plugins.git
      path: packages/device_info_plus/device_info_plus
      ref: main
  connectivity_plus: 
    git:
      url: https://github.com/powntheep/plus_plugins.git
      path: packages/connectivity_plus/connectivity_plus
      ref: main
  flutter_window_close:
    git:
      url: https://github.com/powntheep/flutter_window_close.git
      ref: main
  dart_webrtc:
    path: /Users/pl/Documents/open-source/forks/dart-webrtc
  flutter_webrtc:
    path: /Users/pl/Documents/open-source/forks/flutter-webrtc
  http: 
    git:
      url: https://github.com/dart-lang/http.git
      ref: master
      path: pkgs/http

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - images/logo-dark.svg
